/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.softkik.mcplugins.hermit_tweaks;

import org.junit.Test;
import static org.junit.Assert.*;

public class LibraryTest {
    @Test public void testSomeLibraryMethod() {
        
        assertTrue("true", true);
    }
}
